### ISSUE TITLE
Plugin: Apple BLE Spam

### ISSUE THREAD

**Issue by Ichtestenurmal** [Flipper-XFW/Xtreme-Firmware#384]
### Describe the bug.

Hello folks,

the plugin Apple BLE Spam says when running:

 error:
"Load failed Bluetooth/apple—ble—spam.fap
Found unsatisfied imports"

How can I fix that?

### Reproduction

1. Fresh firmeware install via web installer
2. Start
3. Error

**Comment by Willy-JL** [comment]
You fucked it up. Don't do things you don't understand. Install the latest dev build, don't try to Frankenstein a new app into an incompatible firmware.

**Comment by Ichtestenurmal** [comment]
Where can I find it?

I have not added anything, the plugin came with the latest version that I have installed.

**Comment by Willy-JL** [comment]
No, it's the latest discord dev build. Considering the timing of this issue, I believe I answered you in the discord, but let me know if it was someone else and you still need help

**Comment by khmm12** [comment]
@Ichtestenurmal just use the recent nightly build. 

https://github.com/Flipper-XFW/Xtreme-Firmware/actions/workflows/build.yml

e.g. https://github.com/Flipper-XFW/Xtreme-Firmware/actions/runs/6104041853
<img width="761" alt="image" src="https://github.com/Flipper-XFW/Xtreme-Firmware/assets/4437249/81f42d86-742d-4839-8c66-1a0f6b33bf1c">

**Comment by 0xspade** [comment]
@Willy-JL does the discord dev build requires some kind of subscription or it's free?

**Comment by Willy-JL** [comment]
Free. Just join the discord and get the dev updates role by clicking on it. Or you can get the builds from GitHub actions too

**Comment by 0xspade** [comment]
done installing, now I'm loving it :)

Thanks @Willy-JL

**Comment by khmm12** [comment]
@Willy-JL 

[off-topic]

is there any chance to get an invitation to the discord server? 🙏 I tried a weak ago, but was declined due to new accounts protection and still can't join. The nickname is the same as in GitHub.

**Comment by Willy-JL** [comment]
Try now
